### ISSUE TITLE
urlopen error: certificate verify failed

### ISSUE THREAD

**Issue by fedelibre** [openlilylib/lily-fonts#8]
The script is not working anymore. It seems a certificate issue.

```
$ python install-lily-fonts -d ~/.fonts/ -t ~/lilypond/

Determined font directory:
  /home/fede/.fonts

Determined LilyPond font root directories:
 - /home/fede/lilypond/usr/share/lilypond/current/fonts
No local catalog found.
Do you want to create one in /home/fede/.fonts/CATALOG (y/anything)? y

Downloading font catalog from http://fonts.openlilylib.org ...
An error occured while accessing the catalog:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Aborting
```

**Comment by uliska** [comment]
OK, I see where it's coming from: The domain is now secured by SSL. I
assume (hope) that it's trivial to fix, but I'll have to look into it.

**Comment by fedelibre** [comment]
Great.
A related note: when you've fixed it, what about adding a link to this repo [here](https://github.com/openlilylib/openlilylib/tree/3efffe3859f8fd5db8992ae4d00d16e2d82196bd/ly/stylesheets)?
Where it says:

> Very soon a Python script will available as part of this library that will make the process of downloading, updating and "installing" the fonts a nearly automatic process too.

Or should this script be part of that repo?

**Comment by uliska** [comment]
No, the fonts script should be on its own. Actually I moved it out from openLilyLib because it should be available as a standalone tool.

So yes, I should add that link.

**Comment by uliska** [comment]
I hope this fixed it, please check.
Behind that URL issue (which would probably have been "fixed" by server-side redirection) it turned out that the SSL certificate of that domain wasn't properly set up. A browser would accept it anyway but Python did not.

**Comment by fedelibre** [comment]
Yes, it works now, thanks.
I think that the download of fonts was not included in this script when I first tried it months ago. Very handy. It could be made more *visible*. I didn't realize it until I saw the terminal output.

This sentence (with a typo) in the README:

> From this it can detect additions and pdates on the server, download and extract the archives and manage the links in the LilyPond installation. 

could be rewritten as:

> From this it can watch for additions and updates on the server, download the fonts in the detected font directory and manage the links in the LilyPond installation.

**Comment by uliska** [comment]
> I think that the download of fonts was not included in this script
when I first tried it months ago. Very handy.

Don't know about that, but I consider this a crucial functionality.
However, it remains a temporary need as the way to go is to make
LilyPond access system-installed fonts too - which would remove the
necessity to install fonts in each LilyPond installation/version.

> From this it can detect additions and pdates on the server, download
and extract the archives and manage the links in the LilyPond installation.
>
> could be rewritten as:
>
>

Well, do it ;-)
Works in the web interface and automatically creates a pull request.

**Comment by fedelibre** [comment]
ok, pull #9

**Comment by fedelibre** [comment]
just for the records: I tested it on a fresh machine and found that **ca-certificates** package must be installed in the client, otherwise I get the same error message.

**Comment by uliska** [comment]
As far as I know it depends on the client's OS/distribution which CAs are automatically recognized. So it *may* be necessary to install that package manually.
